Mask/redact password and secure_json_data in grafana_datasource
voxpupuli/puppet-grafana pull request #221
Opened 2020-08-20 12:27 UTC by nmaludy

Previously, when configuring a datasource with a password, the `grafana_datasource` resource would leak on the CLI and in the puppet report:

```shell
Notice: /Stage[main]/Profile::Grafana/Grafana_datasource[postgres]/secure_json_data: secure_json_data changed  to {
  'password' => 'mysweetpassword1'
} (corrective)

```

Now with this fix, the `password` or `secure_json_data` field changes emit the following diff:

```shell
Notice: /Stage[main]/Profile::Grafana/Grafana_datasource[postgres]/secure_json_data: changed [redacted] to [redacted]
```

2020-10-08 15:42 UTC, alexjfisher commented on manifests/install.pp
> +        provider => $grafana::toml_package_provider,
meh.  I still call it a bug.

2020-10-08 15:45 UTC, alexjfisher requested changes
IIRC, this DSL is only available in Puppet 6, so this would break for puppet 5 users??

See https://github.com/puppetlabs/puppetlabs-yumrepo_core/pull/6

2021-01-04 17:55 UTC, bastelfreak commented
I guess a puppet 6 requirement is fine now since Puppet 5 is EoL? @nmaludy can you rebase please?

2021-01-04 18:02 UTC, nmaludy commented
@bastelfreak rebase complete!

2021-01-04 18:06 UTC, bastelfreak commented
can you take a look the linter complains and raise the required puppet version in metadata.json to 6.1.0 ?

2021-01-04 18:19 UTC, bastelfreak approved these changes

2021-01-04 18:21 UTC, merged